### ISSUE TITLE
Web GUI does no updates when MQTT is enabled

### ISSUE THREAD

**Issue by Mogdar-M** [helgeerbe/OpenDTU-OnBattery#200]
### What happened?

I've place the DTU next to the inverter to test if there is a stable wifi connection.

MQTT is enabled and delivers data
![image](https://user-images.githubusercontent.com/129499239/235104005-c27a311a-b413-4fd8-9868-e8bc0559305d.png)
But the Web GUi is not opening
![image](https://user-images.githubusercontent.com/129499239/235104155-54bde877-cc12-4244-a80a-08888e7b51c8.png)

### To Reproduce Bug

I didn't had any issues testing it on the desk so it might be related to the low wifi signal.
But my Ahoy DTU is working om the same dictance perfect

### Expected Behavior

GUI available

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

newest build from yeterday

### Anything else?

Looks like the AP is turning on and off, my phone shows the AP everys minute or so.

No NRF module connected so far
no inverter configured so far

**Comment by Mogdar-M** [comment]
changed wifi network --> no change
changed from powerbank to AV adapter --> no change
![image](https://user-images.githubusercontent.com/129499239/235114747-fb285b02-1377-42ca-8499-6ac70d061b73.png)
I guess the issue is that it is turning on and off

**Comment by helgeerbe** [comment]
What happens if you call the live data api.

Try: `http://opendtu/api/livedata/status` Replace opendtu with your device name or ip address.

Do you see the json document `{"inverters":[{"serial":"xyzzy","name":"Solar","data_age":7,"p.....`? or just null?

If you see null, there might be a memory fragmentation and openDTU was not capable to allocate a big enough memory block. 
Try a reboot, and check if the livedata is shown. 

I know the problem, but I don't have a solution for that. This has to be changed in the original openDTU, but this would be require a lot of work. Sometimes it's just a temporary problem (if you use e. g. prometheus api in parallel).

**Comment by Mogdar-M** [comment]
finally managed to turn off MQTT and now everything is working again.
I've placed the DTU next to the inverter and I'm able to change configuration and save it.

So the issue is MQTT

**Comment by Mogdar-M** [comment]
![image](https://user-images.githubusercontent.com/129499239/235127807-728fc9d4-dc97-41b0-ab80-b04cfe5e2b47.png)

**Comment by helgeerbe** [comment]
Hm, have you enabled any onBattery staff like veredirect.....? What happens if you disable everything related to onBattery. Does MQTT work?

**Comment by Mogdar-M** [comment]
no, it was the lone ESP board, not even an inverter configured.

So I just got status, IP, uptime, rssi und hostname via MQTT

**Comment by helgeerbe** [comment]
Maybe related to #203 

Does the esp reboot?

**Comment by Mogdar-M** [comment]
Nö,

Der ESP lief ja weiter und hat auch weiter Daten geliefert.
Allerdings ja nur rudimentäre Daten, da ja nur der nackte ESP lief.

Sobald ich MQTT abschalten geht die GUi wieder.

Ja, geht an IO Broker, ich Check die Einstellung, ob ich da was anpassen kann
