### ISSUE TITLE
Home Assistant reports "invalid value for number.limit_xxx"

### ISSUE THREAD

**Issue by madmartin** [helgeerbe/OpenDTU-OnBattery#396]
### What happened?

In the Home Assistant Log I see messages about sensor values from OpenDTU-Onbattery which are not in the configured min..max range

### To Reproduce Bug

Having OpenDTU-OnBattery connected to Home Assistant

### Expected Behavior

no error messages

### Install Method

Self-Compiled

### What git-hash/version of OpenDTU?

n/a

### Relevant log/trace output

```Shell
Logger: homeassistant.components.mqtt.number
Source: components/mqtt/number.py:214
Integration: MQTT (documentation, issues)
First occurred: 27. Juni 2023 um 09:31:58 (88182 occurrences)
Last logged: 08:43:40

Invalid value for number.limit_persistent_relative: 0.1 (range 1.0 - 100.0)
Invalid value for number.limit_nonpersistent_absolute: 0.6 (range 10.0 - 2250.0)
Invalid value for number.limit_persistent_absolute: 0.6 (range 10.0 - 2250.0)
Invalid value for number.limit_nonpersistent_absolute: 9.6 (range 10.0 - 2250.0)
Invalid value for number.limit_persistent_absolute: 9.6 (range 10.0 - 2250.0)
```

### Anything else?

This is caused by the upstream OpenDTU code, which configures ranges for the misc. limits. While these min...max limits are fine for OpenDTU, the dynamic PowerLimiter uses limits below the min. limit, causing lots this errors to appear in the log. (in my case ~90000 errors in ~2 months)

I will file a PR to OpenDTU to fix this.

**Comment by joba-1** [comment]
May I chime in here with a similar problem?

My inverter allows raising the limit from 600 to 800W and then reports 800W as relative 133%.
When this is reported to home assistant while max_value is 100 it produces similar error messages and is displayed as an invalid value in related sliders.

Since a slider is used to visualize this, an upper limit is needed to calculate the correct slider position, but it would be nice if the max_value could be configurable.
Alternatively it would probably work to just report it as a number without bounds, not a range with limits?

I currently hard code max_value as 200 and get this:

![grafik](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/32450554/6422fbc4-11bc-4ef0-8206-e183f2fe12c6)

As you can see, there also seems to be a slight rounding error (limits are displayed as 799,8, not the real 800), maybe because the advertised range starts at 1 and not 0?

**Comment by madmartin** [comment]
Note: https://github.com/tbnobody/OpenDTU/pull/1270 has been merged + closed

**Comment by joba-1** [comment]
very nice, and a new release right after the change. Perfect timing, Thank you! :)

Now I only have to figure out how to deal with this [breaking change](https://github.com/tbnobody/OpenDTU/commit/71d1b3b84656e9ee477f3839d9fcb33741ec12ac). My Home Assistant experience is only a few days old…
