### ISSUE TITLE
Refresh time 

### ISSUE THREAD

**Issue by danny1605** [helgeerbe/OpenDTU-OnBattery#691]
### What happened?

The scheduled refreshing time doesnt work. 
![IMG_2126](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/59099140/787bd380-f64e-4920-82e0-20d8ede7fcfa)

### To Reproduce Bug

I dont know 

### Expected Behavior

An Update, which eliminate this bug.

### Install Method

Pre-Compiled binary from GitHub

### What git-hash/version of OpenDTU?

2024.02.19.post1

### Anything else?

![IMG_2125](https://github.com/helgeerbe/OpenDTU-OnBattery/assets/59099140/525fe865-a750-49bd-80ed-2d1cceb99c94)

**Comment by schlimmchen** [comment]
Are you complaining that you set a "Abfrageintervall" of 3 seconds, but the live view tells that the data is 12 seconds old?

**Comment by danny1605** [comment]
> Are you complaining that you set a "Abfrageintervall" of 3 seconds, but the live view tells that the data is 12 seconds old?

That's right, with this setting I change the value ?

**Comment by schlimmchen** [comment]
Not directly, no. The poll interval determines how often the Hoymiles radio controller loops over all registered inverters. In each loop, every inverter is polled sequentially. More inverters means the data age will become bigger. Also, in some rounds, the radio controller might fail to fetch the inverter information. The communication is wireless and hence error-prone. Also, since your HMS-800 is offline, it takes all tries that the radio controller will attempt to reach it until giving up, delaying fetching the inverter data of the online inverter accordingly.

Does this explain why the data age is not 3s when the poll interval is set to 3s?

If so, please close this issue.
